[metadata]
name = crypto_bot_project
version = 0.1.0
description = Telegram bot for crypto tracking

[options]
packages = find:
install_requires =
    flask>=2.0.0
    sqlalchemy>=1.4.0
    python-dotenv
    requests
    telebot
    pytest

[options.extras_require]
dev =
    pytest>=7.0
    pytest-cov
    pylint

# Настройки для pytest
[tool:pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v --cov=user_service --cov=admin_service --cov=crypto_service --cov=bot_service --cov-report=html
asyncio_mode = auto

[flake8]
max-line-length = 120
ignore =
    E722
exclude =
    .git,
    __pycache__,
    venv,
    migrations